apiVersion: v1
kind: Pod
metadata:
    name: ninja26
    namespace: dev
    labels:
        app: frontend
        env: dev
spec:
    containers:
      - image: nginx:1.14.2
        name: frontend
        ports:
        - name:  http
          containerPort:  80
          protocol: TCP
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"